export interface IProfile{
    username: string,
    firstname: string,
    lastname: string,
    bio: string,
    techstack: string[],
    imageUrl: string,
    email: string,
    dob: Date,
    gender: string,
    phonenumber: string,
    country: string,
    profession: string,
    organization: string,
    followers: string[],
}